name: FEniCS

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12

      - name: Conda info
        shell: bash -l {0}
        run: |
          conda info
          which python

      - name: Conda install FEniCS
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes
          conda config --add channels conda-forge
          conda create -n fenicsproject -c conda-forge fenics
          conda activate fenicsproject
          which python
          python -c "from dolfin import *"
          python -c "from fenics import *"

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda activate fenicsproject
          python -m pip install --upgrade pip
          python -m pip install git+https://github.com/dolfin-adjoint/pyadjoint.git@2023.0.0
          python -m pip install pytest
          python -m pip install pytest-cov
          python -m pip install pytest-check
          python -m pip install coveralls
          python -m pip install fdm

      - name: Install current package
        shell: bash -l {0}
        run: |
          conda activate fenicsproject
          python -m pip install -e .

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          conda activate fenicsproject
          python -c "import sys; print('\n'.join(sys.path))"
          python -m pytest --cov=fecr --cov-config=tests/.coveragerc tests/fenics_backend -vvv

      - name: Send coveralls
        shell: bash -l {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          conda activate fenicsproject
          coveralls

      - name: Send codecov
        shell: bash -l {0}
        run: |
          conda activate fenicsproject
          bash <(curl -s https://codecov.io/bash)
