name: DOLFINx

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12

      - name: Conda info
        shell: bash -l {0}
        run: |
          conda info
          which python

      - name: Install DOLFINx and dependencies
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes
          conda config --add channels conda-forge
          conda create -n dolfinxproject python=3.12
          conda activate dolfinxproject
          
          # System dependencies for DOLFINx
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-get install -y gmsh libgmsh-dev petsc-dev slepc-dev
          
          # Install DOLFINx via conda (not pip)
          conda install -c conda-forge fenics-dolfinx mpich pyvista
          
          # Install testing tools
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov pytest-check coveralls fdm
          
          # Install pyadjoint for compatibility with DOLFINx
          python -m pip install git+https://github.com/dolfin-adjoint/pyadjoint.git@2023.0.0

      - name: Install current package
        shell: bash -l {0}
        run: |
          conda activate dolfinxproject
          python -m pip install -e .

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          conda activate dolfinxproject
          python -c "import sys; print('\n'.join(sys.path))"
          python -m pytest --cov=fecr --cov-config=tests/.coveragerc test/test_dolfinx.py -vvv

      - name: Send coveralls
        shell: bash -l {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          conda activate dolfinxproject
          coveralls

      - name: Send codecov
        shell: bash -l {0}
        run: |
          conda activate dolfinxproject
          bash <(curl -s https://codecov.io/bash) 